POST http://localhost:3000/api/usr/login
Content-Type: application/json

{
  "username": "root",
  "password": "nfc929b8894l"
}

###

PUT http://localhost:3000/api/order/
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlY2Y2MTcxZWFhOTA4YjJhNjZkMCIsInBlcm1pc3Npb25zIjpbInJvb3QiXSwiaWF0IjoxNjMwMDU3OTg0LCJleHAiOjE2MzAwNzIzODR9.u9zMIYW_XlBjHS88-pzyr2Dp0PuXmqGPDPOLEe-DHLqMegC9A7MnckE8gAlGXk7qiphj0Vckk9x2-uEiPgavNg

{
  "cart": {
    "61262876a82bbf5071f5332d": 1
  }
}