POST http://localhost:3000/api/usr/login
Content-Type: application/json

{
  "username": "root",
  "password": "nfc929b8894l"
}

###

PUT http://localhost:3000/api/order/
Content-Type: application/json
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlY2Y2MTcxZWFhOTA4YjJhNjZkMCIsInBlcm1pc3Npb25zIjpbInJvb3QiXSwiaWF0IjoxNjMwMTQxNTIyLCJleHAiOjE2MzAxNTU5MjJ9.TSAprRVd2xXSbJjYakASzIEm6xdlHfn284ap7rT71J32gEBvD6-T0QRwFgIsCP52gdaL_S1fAgB3fjJYIkwb3g

{
  "cart": {
    "61262876a82bbf5071f5332d": 1
  }
}

###

GET http://localhost:3000/api/order/JSON/0003?printlist=false
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlY2Y2MTcxZWFhOTA4YjJhNjZkMCIsInBlcm1pc3Npb25zIjpbInJvb3QiXSwiaWF0IjoxNjMwNDg2NjY4LCJleHAiOjE2MzA1MDEwNjh9.mbHHbRz_JUdDJMWpFsk3D2WCUOoMZs48zSy2uaq2_IVsGdJg0sEm5kKd46dRhj6mrVwq3S7IGYC_ZKxT0SIOeA

###

GET http://localhost:3000/api/order/JSON/?from=1630059795720&printlist=true
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlY2Y2MTcxZWFhOTA4YjJhNjZkMCIsInBlcm1pc3Npb25zIjpbInJvb3QiXSwiaWF0IjoxNjMwNDg2NjY4LCJleHAiOjE2MzA1MDEwNjh9.mbHHbRz_JUdDJMWpFsk3D2WCUOoMZs48zSy2uaq2_IVsGdJg0sEm5kKd46dRhj6mrVwq3S7IGYC_ZKxT0SIOeA

###

GET http://localhost:3000/api/order/CSV/?from=0&to=1630059795720
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlY2Y2MTcxZWFhOTA4YjJhNjZkMCIsInBlcm1pc3Npb25zIjpbInJvb3QiXSwiaWF0IjoxNjMwNDg2NjY4LCJleHAiOjE2MzA1MDEwNjh9.mbHHbRz_JUdDJMWpFsk3D2WCUOoMZs48zSy2uaq2_IVsGdJg0sEm5kKd46dRhj6mrVwq3S7IGYC_ZKxT0SIOeA

###

GET http://localhost:3000/api/order/CSV/
Authorization: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBlY2Y2MTcxZWFhOTA4YjJhNjZkMCIsInBlcm1pc3Npb25zIjpbInJvb3QiXSwiaWF0IjoxNjMwNDg2NjY4LCJleHAiOjE2MzA1MDEwNjh9.mbHHbRz_JUdDJMWpFsk3D2WCUOoMZs48zSy2uaq2_IVsGdJg0sEm5kKd46dRhj6mrVwq3S7IGYC_ZKxT0SIOeA
