POST http://localhost:3001/api/cucina1/order
Content-Type: application/json

{
  "payload": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXJ0IjpbeyJwcm9kdWN0Ijp7InRpdGxlIjoiY2V0cmlvbG8iLCJwcmljZSI6NjAwLCJjYXRlZ29yeSI6IkNVQ0lOQSIsInN0b2NrIjo0MiwiZGVzY3JpcHRpb24iOiJsb2wiLCJfaWQiOiI2MTI2Mjg3NmE4MmJiZjUwNzFmNTMzMmQifSwicXRhIjozfV0sImNvZGUiOiIwMDAzIiwidG90YWwiOjMwMDAsImlhdCI6MTYzMDQ4Mzc5NiwiZXhwIjoxNjMwNDk4MTk2fQ.bwdr2Vkggtm-dmIdPi2CRCBNEVRcdT1rQAunBmh2T-xuDf3fNx09VXWiLsc9wLylCM1PzdZmW5xMFfQcUjo37A"
}